[package]
name = "ph-sht45-hts"
version = "0.1.0-incubating.1"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Incubating unpublished async no_std Rust driver for the Sensirion SHT45 humidity and temperature sensor over abstract I2C. No supported operations yet."
repository.workspace = true
readme = "README.md"
publish = false
keywords = ["embedded", "no-std", "sht45", "hts"]
categories = ["embedded", "hardware-support", "no-std"]

[dependencies]
